version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: . # In this location . where is the root here is the dockerfile for this image container
      dockerfile: nginx.Dockerfile # Build Custom Docker IMage in this file
    # image: nginx-image
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/ # Bind Mounting technique
